baseURL = "https://lecitatiba.com.br/"
languageCode = "pt-br"
title = "Lar Espírita Cristão"
theme = "mainroad"
publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  mainSections = ["post"]
  description = "Evangelho, acolhimento e consolação em Itatiba"
  subtitle = "Fora da Caridade não há Salvação"
  highlightColor = "#e22d30"
  customCSS = ["css/custom.css"]
  favicon = "favicon.ico" 
  
  # Configurações para o player ao vivo (YouTube)
  youtubeChannelID = "UCW7NoMwjuc5tdLgPhjShlIQ"
  
  # ID do Spotify (Substitua quando criar a conta no Spotify for Podcasters)
  spotifyShowID = "06cqVyhjydGRHPlnGw8AxD"

  [params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    # Adicionei 'zeno_live' e 'spotify_playlist' na ordem lógica:
    widgets = ["search", "live_audio", "recent", "agenda_custom", "spotify", "mapa_custom", "categories"]

  [params.footer]
    copyrightText = "Lar Espírita Cristão"

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 1

# [[menu.main]]
# name = "História"
# url = "/historia/"
# weight = 2

# removi o agenda

[[menu.main]]
  name = "Pinga-Fogo"
  url = "/pinga-fogo/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
